version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.11.3
    container_name: contract-rag-qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - contract-rag-network

networks:
  contract-rag-network:
    driver: bridge
